import { Deal } from "./types";

export const initialDeals: Deal[] = [
  {
    id: "1",
    dealNumber: "01",
    category: "新規開拓",
    companyName: "東京テクノロジー株式会社",
    contactName: "田中 太郎",
    stage: "商談中",
    nextAction: "決裁者との面談を設定",
    assignee: "村上",
    scheduledDate: "2026-04-03",
    result: "部長から前向きな回答あり",
    hypothesis: "DX推進の予算が確保されている可能性が高い",
    wonAmount: 0,
    createdAt: "2026-01-15",
    updatedAt: "2026-03-25",
  },
  {
    id: "2",
    dealNumber: "02",
    category: "新規開拓",
    companyName: "大阪メディア株式会社",
    contactName: "佐藤 次郎",
    stage: "提案",
    nextAction: "提案資料の修正・再送付",
    assignee: "松田",
    scheduledDate: "2026-04-05",
    result: "競合2社と比較検討中とのこと",
    hypothesis: "価格よりも導入サポート体制を重視している",
    wonAmount: 0,
    createdAt: "2026-02-01",
    updatedAt: "2026-03-20",
  },
  {
    id: "3",
    dealNumber: "03",
    category: "新規開拓",
    companyName: "名古屋製造株式会社",
    contactName: "高橋 三郎",
    stage: "ヒアリング",
    nextAction: "工場見学のアレンジ",
    assignee: "土田",
    scheduledDate: "2026-04-10",
    result: "現場の課題を詳細にヒアリング済み",
    hypothesis: "3拠点同時導入は予算的に厳しく、段階導入になりそう",
    wonAmount: 0,
    createdAt: "2026-03-01",
    updatedAt: "2026-03-22",
  },
  {
    id: "4",
    dealNumber: "04",
    category: "海外",
    companyName: "Shanghai Tech Co., Ltd.",
    contactName: "王 明",
    stage: "見積",
    nextAction: "見積書の条件交渉",
    assignee: "吉田",
    scheduledDate: "2026-04-07",
    result: "フェーズ1の見積りを送付済み",
    hypothesis: "追加要件が出る可能性が高い",
    wonAmount: 0,
    createdAt: "2026-01-20",
    updatedAt: "2026-03-18",
  },
  {
    id: "5",
    dealNumber: "05",
    category: "海外",
    companyName: "Singapore Solutions Pte. Ltd.",
    contactName: "Tan Wei Ming",
    stage: "受注",
    nextAction: "契約書の最終確認",
    assignee: "小澤",
    scheduledDate: "2026-04-01",
    result: "契約締結済み",
    hypothesis: "",
    wonAmount: 12000000,
    createdAt: "2025-12-10",
    updatedAt: "2026-03-15",
  },
  {
    id: "6",
    dealNumber: "06",
    category: "新規開拓",
    companyName: "横浜コンサルティング株式会社",
    contactName: "中村 六郎",
    stage: "未アプローチ",
    nextAction: "初回コンタクトのメール送信",
    assignee: "星野",
    scheduledDate: "2026-04-02",
    result: "",
    hypothesis: "問い合わせ内容からニーズは高そう",
    wonAmount: 0,
    createdAt: "2026-03-20",
    updatedAt: "2026-03-20",
  },
  {
    id: "7",
    dealNumber: "07",
    category: "OEM",
    companyName: "神戸エレクトロニクス株式会社",
    contactName: "小林 七郎",
    stage: "失注",
    nextAction: "次年度に再提案予定",
    assignee: "村上",
    scheduledDate: "2026-10-01",
    result: "競合に価格面で敗退",
    hypothesis: "",
    wonAmount: 0,
    createdAt: "2025-11-05",
    updatedAt: "2026-03-10",
  },
  {
    id: "8",
    dealNumber: "08",
    category: "OEM",
    companyName: "仙台ヘルスケア株式会社",
    contactName: "加藤 八郎",
    stage: "アポイントメント",
    nextAction: "初回訪問の日程調整",
    assignee: "松田",
    scheduledDate: "2026-04-08",
    result: "電話で概要を説明済み",
    hypothesis: "セキュリティ要件が厳しいため技術面の説明が鍵",
    wonAmount: 0,
    createdAt: "2026-03-05",
    updatedAt: "2026-03-24",
  },
  {
    id: "9",
    dealNumber: "09",
    category: "海外",
    companyName: "Bangkok Trading Co., Ltd.",
    contactName: "Somchai P.",
    stage: "提案",
    nextAction: "プレゼン結果の確認連絡",
    assignee: "土田",
    scheduledDate: "2026-04-04",
    result: "提案プレゼン完了",
    hypothesis: "来週中に結果が出る見込み",
    wonAmount: 0,
    createdAt: "2026-02-15",
    updatedAt: "2026-03-21",
  },
  {
    id: "10",
    dealNumber: "10",
    category: "OEM",
    companyName: "京都クリエイティブ株式会社",
    contactName: "井上 十郎",
    stage: "納品",
    nextAction: "納品後フォローアップ",
    assignee: "吉田",
    scheduledDate: "2026-04-15",
    result: "納品完了、運用開始",
    hypothesis: "",
    wonAmount: 7000000,
    createdAt: "2026-01-10",
    updatedAt: "2026-03-26",
  },
];
